# Site settings
title: invrse - the game development blog
email: thaisrobba@gmail.com
author: Thaís Robba
description: "Educational blog on game design and development, including topics like programming, tools, processes and techniques."
baseurl: "http://thaisrobba.github.io/invrse"
url: "http://thaisrobba.github.io/invrse"
google_analytics: UA-55865997-1
animated: false

# Build settings
markdown: kramdown
permalink: pretty
#paginate: 3
sass:
  compressed: true

gems: [jekyll-sitemap]
