# Site settings
title: invrse
email: ottorobba@gmail.com
author: Otto Robba
description: "Not doing what is expected of me or: how I learned to stop worrying and love programming."
baseurl: ""
url: "http://www.invrse.co"
google_analytics:
animated: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass:
  compressed: true

